2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA.java
분석탭 임시로 만들었습니다. 확인 부탁드립니다.
이..이렇게 하면 되나?
=> 분석탭 (임시) 완성

2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/Home.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS_frag1.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS_pager_frag1.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS_pager_frag2.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS_pager_frag3.java, 2021_2_front/210811_CapstoneDesign/app/src/main/res/layout/fs.xml, 2021_2_front/210811_CapstoneDesign/app/src/main/res/layout/fs_frag1.xml, 2021_2_front/210811_CapstoneDesign/app/src/main/res/layout/fs_pager_frag1.xml, 2021_2_front/210811_CapstoneDesign/app/src/main/res/layout/fs_pager_frag2.xml, 2021_2_front/210811_CapstoneDesign/app/src/main/res/layout/fs_pager_frag3.xml, 2021_2_front/210811_CapstoneDesign/app/src/main/res/menu/fs_frag1_menu.xml
* 설명 : 상태탭 뼈대 만드는중. 아직 작업 더 많이 남았지만 우선 commit합니다.
* 추가 파일들
1. home_fragments(folder) : FS_frag1, FS_pager_frag1, FS_pager_frag2, FS_pager_frag3 생성.
2. R/layout(folder) : fs_frag1, fs_pager_frag1.xml, fs_pager_frag2.xml, fs_pager_frag3.xml
3. menu(folder) : fs_frag1_menu
* 수정 파일들
1. R/layout(folder) : fs.xml
2. home_fragments(folder) : FS.class
*p.s : 다시한번 강조하지만 아직 수정해야 하는 부분 많이 있음
=> 상태탭 1차 commit 2021-08-17작업 내용

2021_2_front/210811_CapstoneDesign/app/build.gradle, 2021_2_front/210811_CapstoneDesign/app/src/main/AndroidManifest.xml, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/Register.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/RegisterRequest.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/RegisterResponse.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/RetrofitClient.java, 2021_2_front/210811_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/initMyApi.java
=> front http 통신 테스트.

2021_2_backEnd/.gitignore, 2021_2_backEnd/backEnd/__init__.py, 2021_2_backEnd/backEnd/test/test.py, 2021_2_backEnd/backEnd/user/login.py, 2021_2_backEnd/backEnd/user/logintest.py, 2021_2_backEnd/backEnd/user/logout.py, 2021_2_backEnd/backEnd/user/mail.py, 2021_2_backEnd/backEnd/user/register.py, 2021_2_backEnd/requirements.txt
1. apache, wsgi와 연동을 통해서 서버를 열기 위해 프로젝트의 import구조를 변경했습니다.
- 실행시 flask run이 아닌 backEnd 폴더에서 python __init__.py로 실행해야 함
2. mail인증 api 생성 (http://baseurl/user/email) *baseurl은 테스트 원할 시 알려드림
- 위 url로 {"email" : "anyemail@anydomain.xx"}의 형식으로 json객체를 보내면 보낸 주소로 인증 코드를 포함한 email발송후 반환값으로 {"message" : code}의 형식으로 json객체를 반환
- 반환값 형식은 추후 수정 예정 ({"message" : success or fail, "code" : code}의 형식으로)
=> apache, wsgi와의 연동을 위한 프로젝트 구조, import 형식 변경, mail인증 api

2021_2_backEnd/backEnd/__init__.py, 2021_2_backEnd/backEnd/user/register.py
=> api문서 내용 조금 수정

2021_2_backEnd/backEnd/user/logout.py, 2021_2_backEnd/backEnd/user/register.py
api문서의 example json model이름들을 재설정해서 문서에 나타나는 오류 수정
=> API문서의 example model이름 재설정

2021_2_front/210830_CapstoneDesign/app/build.gradle, 2021_2_front/210830_CapstoneDesign/app/src/main/AndroidManifest.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/Home.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/MainActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/PreferenceManager.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/initMyApi.java, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/fs.xml
1. 어플리케이션 최소 sdk api level을 30 -> 28로 조정(제 휴대폰이 28이라...)
2. Google fit 작업하던 내용 적용.
- Listener 추가/삭제
- Mymenu Item들의 동적 할당 및 제거.
- 어떤 정보를 보고자 하는지에 따른 Subsribe.
- 약간의 코드 최적화(이 부분은 추후에 더 할 예정)
- 목표 걸음 수 ProgressBar부분 수정
3. MainActivity에서 google fit 관련 정보를 위한 권한 받음.
4. 3번에서 받은 권한이 제대로 받아졌는지 SharedPreferenceData에 저장(Application context로 저장).
=> Google fit Update

2021_2_backEnd/backendDB.sql
kakaoAccessToken, kakaoRefreshToken 컬럼 생성
=> DB 구조 파일 업데이트

2021_2_front/210830_CapstoneDesign/.idea/gradle.xml, 2021_2_front/210830_CapstoneDesign/.idea/runConfigurations.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/MainActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA_frag1.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/GoogleFitExamples.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/MyGoogleFit.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/PeriodicData.java, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/fs.xml
수정자 : 김영우
Commit 내용 요약:
- Google fit 활용 함수 변경.
- Listener 대신 Timer를 사용하여 주기적으로 데이터 갱신하도록 함.
- My메뉴에서 볼 수 있는 데이터 수정.
변경 전 : 걸음수, 칼로리, 이동거리, 평균속도.
변경 후 : 칼로리, 이동거리, 이동 시간.(걸음수는 항상 표시해 줌으로 My 메뉴에서 제외함.)
=> Create_Google fit class

2021_2_backEnd/.gitignore, 2021_2_backEnd/backEnd/service/image.py, 2021_2_backEnd/backEnd/service/profile.py, 2021_2_backEnd/backEnd/swaggerModel.py, 2021_2_backEnd/backEnd/user/mail.py
1. profile api의 request, response model 수정
- 생년월일(dateOfBirth), 거주지(abode)를 모델에 추가
2. mail api 수정
- userEmail path의 설명 추가
3. image api를 accesstoken없이 접근 가능하도록 설정
=> profile, mail api 문서 수정, gitignore 수정

2021_2_backEnd/backEnd/__init__.py, 2021_2_backEnd/backEnd/service/friends.py, 2021_2_backEnd/backEnd/service/health_data.py, 2021_2_backEnd/backEnd/service/ranking.py, 2021_2_backEnd/backEnd/user/naver.py
1. ranking api 작성
2. healthData api 수정
put을 post로 post를 get으로 형식과 내용 완전히 수정
3. friends api 수정
page 기능 삭제
4. api 문서 수정
payload 설명 추가
성공 사유 및 리턴타입 명시
=> ranking api 작성, 몇몇 api 수정, api 문서 수정

2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA_frag2.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA_frag3.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA_frag4.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FS.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/Friend.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/MyGoogleFit.java, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/fa_frag1.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/fa_frag2.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/fa_frag4.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/fs.xml
위치탭에서 7일 30일 단위로 그래프 찍는 함수 Ver 1.0 만들어서 업데이트 합니다.
=> 위치탭 Ver 1.0

2021_2_backEnd/backEnd/service/profile.py, 2021_2_backEnd/backEnd/user/auth.py, 2021_2_backEnd/backEnd/user/kakao.py, 2021_2_backEnd/backEnd/user/register.py, 2021_2_backEnd/backendDB_ver_10_06.sql
1. user table column생성
- 생년월일 저장하는 dateOfBirth, 거주지를 저장하는 abode column 생성
2. profile api 기능 추가
- 생년월일과 거주지를 수정할 수 있는 기능 추가
- 현재 프로필사진 수정 기능을 빼고는 모두 작성 완료
=> user table column생성, profile api 기능 추가

2021_2_backEnd/backEnd/database.py, 2021_2_backEnd/backEnd/service/profile.py
1. profile api수정
- 2가지의 route를 사용 : service/profile, service/profile/{friendEmail}
- get method(프로필 정보 가져오기)를 사용할 때는 두 가지의 route 모두 사용 가능
- service/profile : 자신의 프로필 정보, service/profile/{friendEmail} : 친구의 프로필 정보
- put method(프로필 정보 수정)를 사용할 때는 오직 자신의 정보만을 수정할 수 있어야 하므로 service/profile만 사용 가능
=> profile api 수정

2021_2_backEnd/backEnd/service/profile.py, 2021_2_backEnd/backendDB_table.sql
db 수정
- 'abode', 'dateOfBirth' 컬럼 추가
- 'profilePhoto' 컬럼 디폴트값 null로 변경
=> db수정, profile 오류 수정

2021_2_backEnd/backEnd/service/friends.py, 2021_2_backEnd/backEnd/service/ranking.py, 2021_2_backEnd/backEnd/swaggerModel.py, 2021_2_backEnd/backendDB_test.sql
1. 친구 요청 목록 리턴 형태 수정
2. 친구 목록, 친구 요청 api 수정
3. 랭킹 목록 수정
4. 랭킹 관련 DB 데이터 추가
=> friends.py ranking.py DB_test 수정

2021_2_backEnd/backEnd/service/notification.py, 2021_2_backEnd/backEnd/service/profile.py, 2021_2_backEnd/backEnd/user/fcmToken.py
1. profile api오류 수정
- 자잘한 문법오류 수정
- 파라미터 검사 삭제
2. fcm api 수정
- fcm을 data message형식으로 보내도록 수정
- fcmToken api에서 문법 오류 수정
=> profile api 오류 수정, fcm api 수정

2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/RetrofitClient.java
appContext 를 확인하여 appContext가 null인지 확인하는 부분 추가
=> KimYoungwoo's pr

2021_2_front/210830_CapstoneDesign/.idea/gradle.xml, 2021_2_front/210830_CapstoneDesign/.idea/runConfigurations.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/CFriendListActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA_frag1.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/MyGoogleFit.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FriendCaloriesDataResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FriendDistanceDataResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FriendMvMinDataResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FriendStepDataResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/initMyApi.java
우선 걸음수 분석에만 추가해 놓았고 다른 곳에는 익일 코드 정리하면서 적용할 예정
=> 친구 비교 작업 완료

2021_2_backEnd/backEnd/swaggerModel.py
profile get api에서 step_count의 반환 자료형을 integer로 변경
=> swagger model 수정

2021_2_front/210830_CapstoneDesign/.idea/gradle.xml, 2021_2_front/210830_CapstoneDesign/.idea/runConfigurations.xml, 2021_2_front/210830_CapstoneDesign/app/build.gradle, 2021_2_front/210830_CapstoneDesign/app/google-services.json, 2021_2_front/210830_CapstoneDesign/app/src/main/AndroidManifest.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/CFriendListActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/FCM/FireBaseMS.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/FriendListActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/Home.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/MySQLite/DataBases.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/MySQLite/DbOpenHelper.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA_frag1.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FL.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/Message/Message.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/Message/MessageActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/Message/MessageListAdapter.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/note, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/AddFriendRequest.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/AddFriendResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FCM/FcmTokenRequest.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FCM/FcmTokenResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/RetrofitClient.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/initMyApi.java, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/activity_message.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/message_list_item.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/res/menu/message_menu.xml, 2021_2_front/210830_CapstoneDesign/build.gradle
=> 친구 리스트. 메시지 함, FCM 추가

2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/CFriendListActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/FCM/FireBaseMS.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/FriendListActivity.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/Login.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/MySQLite/DataBases.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FA_frag2.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FL.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/FR_ListAdapter.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/home_fragments/Message/MessageListAdapter.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FCM/FcmMessageRequest.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FCM/FcmMessageResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FriendListResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FriendRequestList/FriendRequestListResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/FriendRequestList/FriendRequestedListResponse.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/ProceedFriendRequest/CancelFR_Request.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/ProceedFriendRequest/CancelFR_Response.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/ProceedFriendRequest/ProceedFR_Request.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/ProceedFriendRequest/ProceedFR_Response.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/RetrofitClient.java, 2021_2_front/210830_CapstoneDesign/app/src/main/java/com/example/capstonedesign/retrofit/initMyApi.java, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/activity_friendlist.xml, 2021_2_front/210830_CapstoneDesign/app/src/main/res/layout/friend_reqeuset_item.xml
=> 친구 요청, 친구 목록, 메시지함, FCM 메시지 기능 추가

2021_2_backEnd/backEnd/__init__.py, 2021_2_backEnd/backEnd/config.py, 2021_2_backEnd/backEnd/service/friends.py, 2021_2_backEnd/backEnd/service/ranking.py, 2021_2_backEnd/backEnd/user/kakao.py
1. fcmServerKey 변경
2. friends.py의 친구 요청시 푸시 메시지를 발송하는 기능 추가
3. 자잘한 부분 수정
=> api자잘한 오류 수정, friends.py에 fcm기능 추가, config.py 수정

2021_2_backEnd/backEnd/__init__.py, 2021_2_backEnd/backEnd/service/encourage.py, 2021_2_backEnd/backEnd/service/ranking.py
1. yesterday 일정추가
2. 11/30 랭크에서 유동적인 ranking 집계하도록 변경
=> 스케줄 조정 및 일부변경
